---
- hosts: all
  gather_facts: False

  tasks:

  - name: Execute API call to return backup information
    uri:
      force_basic_auth: yes
      method: GET
      password: "{{ nsxmgr_cli_password}}"
      user: "{{ nsx_username }}"
      headers:
        Content-Type: "application/json"
        Accept: "application/json"
      url: "https://{{ inventory_hostname }}/api/1.0/appliance-management/backuprestore/backupsettings"
      validate_certs: no
      return_content: yes
    register: nsx_api
    failed_when: "'SFTP' not in nsx_api.json.ftpSettings.transferProtocol"
    delegate_to: localhost

  - name: debug nsx_api variable
    debug:
      var: nsx_api.json.ftpSettings.transferProtocol
      verbosity: 2


# Usage example:
# ansible-playbook verify-backups.yaml -i inventory --limit 'nsx-01.demo.vmware.com'
